actions:
  1:
    action: delete_indices
    description: blablabla
    options:
      ignore_empty_list: True
      timeout_override:
      disable_action: False
      allow_ilm_indices: true
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-
    - filtertype: space
      disk_space: 100
      use_age: True
      source: creation_date